# Generated by Django 2.2.5 on 2019-10-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0004_auto_20191018_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
