# Generated by Django 2.2.5 on 2019-10-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0005_auto_20191018_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo1',
            old_name='choice_text',
            new_name='photo1_text',
        ),
    ]
