# Generated by Django 2.2.5 on 2019-10-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0006_auto_20191018_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
