# Generated by Django 2.2.5 on 2019-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='null', height_field=300, upload_to='media/img', width_field=300),
            preserve_default=False,
        ),
    ]
