# Generated by Django 2.2.5 on 2019-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0011_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(help_text='150x150px', upload_to='media/img/', verbose_name='loft12.png'),
        ),
    ]
