# Generated by Django 2.2.5 on 2019-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0012_auto_20191020_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='loft12.png'),
        ),
    ]
