# Generated by Django 2.2.5 on 2019-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0013_auto_20191020_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/', verbose_name='Грузи епт'),
        ),
    ]
