# Generated by Django 2.2.5 on 2019-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0015_auto_20191028_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='грузи картинку'),
        ),
    ]
