# Generated by Django 2.2.5 on 2019-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintheme', '0017_photoframeless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_text',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='photoframeless',
            name='PhotoFrameless_text',
            field=models.CharField(max_length=35),
        ),
    ]
