# Generated by Django 2.2.5 on 2019-11-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintheme', '0022_gate_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='photo_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoframeless',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='frameless_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvc',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pvc_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_text',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='Загрузка фото'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='Загрузка фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_text',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photoframeless',
            name='PhotoFrameless_text',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='photoframeless',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='Загрузка фото'),
        ),
        migrations.AlterField(
            model_name='photoframeless',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='pvc',
            name='Pvc_text',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='pvc',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='Загрузка фото'),
        ),
        migrations.AlterField(
            model_name='pvc',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
