# Generated by Django 2.2.5 on 2019-11-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintheme', '0023_auto_20191110_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='metall',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='metall_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
    ]
