# Generated by Django 3.0.3 on 2020-02-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintheme', '0024_metall_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metall',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/gallery/', verbose_name='Загрузка фото'),
        ),
        migrations.AlterField(
            model_name='metall',
            name='metall_text',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='metall',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата убликации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название поста'),
        ),
    ]
